name: Purge

on: 
  push:
    branches: 
      - master # build master branch only

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: build
      run: |
        yarn install
        yarn run build
        
    - name: purge
      run: |
        curl https://purge.jsdelivr.net/gh/ChenYFan/CDN/
